const hotels = 
[
    { id: 1, name: "Hotel Taj Mahal", location: "Agra, Uttar Pradesh", price: 250, availability: true, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYBtrbqn8vrnp4KHqX-svewpON50w8clKJFQ&s" },
    { id: 2, name: "The Oberoi", location: "Mumbai, Maharashtra", price: 400, availability: true, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQFN_3pZRRxAduT6ieX9u8Ja6IWpEnOvJlDtQ&s" },
    { id: 3, name: "Radisson Blu", location: "Delhi", price: 200, availability: true, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1R4avNai45OP21xxiuQlJNndDhfqPzHFf1g&s" },
    { id: 4, name: "JW Marriott", location: "Bengaluru, Karnataka", price: 300, availability: false, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJ3yVze7ShDfnotQhDa-7kB3Tw4347gGuS9w&s" },
    { id: 5, name: "ITC Grand Chola", location: "Chennai, Tamil Nadu", price: 350, availability: true, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ3Xgq2geiRrXcqae-YMuTIT_2_6N8c6QKSjg&s" },
    { id: 6, name: "Hyatt Regency", location: "Kolkata, West Bengal", price: 220, availability: true, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrK6yQkXW17ZaJIftyZv_TDWTZkX9PUyYfjg&s" },
    { id: 7, name: "Leela Palace", location: "Bengaluru, Karnataka", price: 450, availability: false, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTE4tyBQUMul4jMPjKf7mPT0aPdbCt8aZ2Ifg&s" },
    { id: 8, name: "Novotel", location: "Hyderabad, Telangana", price: 150, availability: true, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-aAfN96r4Pmwd4v5iiPpFTwyPe0CEhP_dHg&s" },
    { id: 9, name: "Hilton", location: "Pune, Maharashtra", price: 300, availability: true, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9g36iRFWGN4VMmIPcosR2DGyWmMN3yH76Iw&s" },
    { id: 10, name: "The Westin", location: "Gurgaon, Haryana", price: 270, availability: true, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTO5Loatk-REl2u_r7UmkoZFUDC03_VHgGd8Q&s" },
    { id: 11, name: "Taj Lands End", location: "Mumbai, Maharashtra", price: 380, availability: false, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRPB6mGncuL1TfzZkjSKV4umwmxhz7S25JZOQ&s" },
    { id: 12, name: "Sheraton Grand", location: "Bengaluru, Karnataka", price: 320, availability: true, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQgz0PLjbf2wlY1pG-4m0rlFETMGbdeNEqz0w&s" },
    { id: 13, name: "The Leela", location: "Goa", price: 500, availability: true, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_BUhQI8vqSAimn_6yEE2XehTqe2ZiEkNjyA&s" },
    { id: 14, name: "ITC Mughal", location: "Agra, Uttar Pradesh", price: 260, availability: true, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSvOKwxBDkoX_3kt4xHtfsf-Pgeujk7tnC8tw&s" },
    { id: 15, name: "The Taj Mahal Palace", location: "Mumbai, Maharashtra", price: 450, availability: false, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRT4Y1lJPwEL--w-301kzSk_bG6ci3gsqtNxA&s" },
    { id: 16, name: "Radisson Blu", location: "Jaipur, Rajasthan", price: 210, availability: true, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTUv9yO3f7KBCiRjYcEdSdYi9Mo8Qvp-hWVjw&s" },
    { id: 17, name: "Le Meridien", location: "Ahmedabad, Gujarat", price: 240, availability: true, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQKU4JgtWva18IcCKcuKgIrbhZqI9gt0a2biA&s" },
    { id: 18, name: "Park Plaza", location: "Chennai, Tamil Nadu", price: 180, availability: true, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQTUyTpgaWcIrVBpdyu_ionDTVGZ5DBDVH7gw&s" },
    { id: 19, name: "DoubleTree by Hilton", location: "Hyderabad, Telangana", price: 220, availability: true, image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS815SAUUl8INBq2c_6kDHyuAeiWojJbc64Og&s" },
    { id: 20, name: "The Lalit", location: "New Delhi", price: 300, availability: false, image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/04/53/a5/cf/the-lalit-new-delhi.jpg?w=700&h=-1&s=1" },
    { id: 21, name: "Marriott Hotel", location: "Kolkata, West Bengal", price: 270, availability: true, image: "https://cache.marriott.com/content/dam/marriott-renditions/CCUFI/ccufi-vertex-8255-hor-feat.jpg?output-quality=70&interpolation=progressive-bilinear&downsize=1920px:*" },
    { id: 22, name: "Fortune Park", location: "Bhopal, Madhya Pradesh", price: 150, availability: true, image: "https://housing-images.n7net.in/4f2250e8/611d5593689cd38d575c19c9465b8b53/v0/medium/fortune_soumya_santosa-bagli_village-bhopal-fortune_soumya_housing.jpeg" },
    { id: 23, name: "Crowne Plaza", location: "Surat, Gujarat", price: 230, availability: true, image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2b/f6/54/90/facade.jpg?w=700&h=-1&s=1" },
    { id: 24, name: "Eros Hotel", location: "New Delhi", price: 290, availability: true, image: "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/2d/cc/96/8d/facade-shot-finished.jpg?w=700&h=-1&s=1" },
    { id: 25, name: "The Ashok", location: "New Delhi", price: 250, availability: true, image: "https://www.bandbaajabarat.com/images/postgallery/167298573528theashokhl.jpg" },
    { id: 26, name: "Taj Gateway", location: "Kochi, Kerala", price: 350, availability: false, image: "https://luxoticholidays.com/backend/web/hotels/taj%20gateway%20kochi-1514471230.jpg" },
    { id: 27, name: "Trident", location: "Udaipur, Rajasthan", price: 300, availability: true, image: "https://www.tridenthotels.com/-/media/trident-hotel/trident-udaipur/udaipur-overview/spa--wellness/desktop-765x580/pool.jpg" },
    { id: 28, name: "Ramada", location: "Coimbatore, Tamil Nadu", price: 200, availability: true, image: "https://content.jdmagicbox.com/comp/bangalore/m8/080pxx80.xx80.200708210618.v1m8/catalogue/ramada-by-wyndham-yelahanka-bangalore-4-star-hotels-jh4ejip19s.jpg" },
    { id: 29, name: "Holiday Inn", location: "Chandigarh", price: 220, availability: true, image: "https://digital.ihg.com/is/image/ihg/holiday-inn-panchkula-4023878270-2x1" },
    { id: 30, name: "Grand Mercure", location: "Vadodara, Gujarat", price: 260, availability: true, image: "https://www.ahstatic.com/photos/9278_ho_00_p_1024x768.jpg" },
];

export default hotels;
